In [34]:
import numpy as np

In [35]:
size = 10000

In [36]:
big_array = np.random.rand(size)
big_array

array([0.32851803, 0.73788175, 0.14917657, ..., 0.42170695, 0.14407475,
       0.44755725], shape=(10000,))

In [ ]:
%timeit big_array2 = np.power(2, big_array)

302 μs ± 6.9 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [38]:
Anii = 20
Anii

20

In [39]:
Anii = 'EUBA_FHI'
Anii

'EUBA_FHI'

In [40]:
np.random.randn(10)

array([-0.33471481,  0.35476749, -0.70936577,  0.79214947, -0.3914126 ,
       -0.05135542,  0.79535303,  0.04196594, -0.81622323, -0.78182906])

In [ ]:
np.random.randint(10)

Type:        module
String form: <module 'numpy.random' from 'C:\\Users\\filip\\AppData\\Roaming\\Python\\Python313\\site-packages\\numpy\\random\\__init__.py'>
File:        c:\users\filip\appdata\roaming\python\python313\site-packages\numpy\random\__init__.py
Docstring:  
Random Number Generation

Use ``default_rng()`` to create a `Generator` and call its methods.

=============== =========================================================
Generator
--------------- ---------------------------------------------------------
Generator       Class implementing all of the random number distributions
default_rng     Default constructor for ``Generator``
=============== =========================================================

============================================= ===
BitGenerator Streams that work with Generator
--------------------------------------------- ---
MT19937
PCG64
PCG64DXSM
Philox
SFC64
============================================= ===

====================================

In [42]:
vector = np.arange(6)
vector

array([0, 1, 2, 3, 4, 5])

In [43]:
vector.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [44]:
pole_num_1 = np.arange(9).reshape(3,3)
pole_num_1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:

pole_num_2 = pole_num_1
pole_num_2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
pole_num_2[2,2] = 69
pole_num_2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7, 69]])

In [47]:
pole_num_1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7, 69]])

In [48]:
pole_num_3 = pole_num_1.copy()
pole_num_3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7, 69]])

In [49]:
pole_num_3[2,2] = 71
pole_num_3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7, 71]])

In [50]:
pole_num_1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7, 69]])

In [51]:
# This is a commentáris

In [52]:
# Broadcasting example

In [60]:
pole_num_1 + 10

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 79]])

In [62]:
pole_num_1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7, 69]])

In [63]:
pole_num_1 < 40

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False]])

In [ ]:
# Comparison

In [65]:
(pole_num_1 < 40) & (pole_num_1 >= 4)

array([[False, False, False],
       [False,  True,  True],
       [ True,  True, False]])